import express from 'express';
import userRoutes from './userRoutes.js';
import addressRoutes from './addressRoutes.js';
import productRoutes from './productRoutes.js';
import searchRoutes from './searchRoutes.js';
import cartRoutes from './cartRoutes.js';
import checkoutRoutes from './checkoutRoutes.js';
import orderTrackingRoutes from './orderTrackingRoutes.js';
import ordersRoutes from './ordersRoutes.js';
import sellerRoutes from './sellerRoutes.js';
import sellerProductRoutes from './sellerProductRoutes.js';
import sellerOrderRoutes from './sellerOrderRoutes.js';
import promotionRoutes from './promotionRoutes.js';
import profileRoutes from './profileRoutes.js';
import communityRoutes from './communityRoutes.js';
import notificationRoutes from './notificationRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import analyticsRoutes from './analyticsRoutes.js';
import paymentMethodRoutes from './paymentMethodRoutes.js';
import returnsRoutes from './returnsRoutes.js';
import reviewRoutes from './reviewRoutes.js';
import voucherRoutes from './voucherRoutes.js';
import helpRoutes from './helpRoutes.js';
import hyperlocalRoutes from './hyperlocalRoutes.js';
import inventoryRoutes from './inventoryRoutes.js';
import whatsappRoutes from './whatsappRoutes.js';
import legalRoutes from './legalRoutes.js';
import furnitureRoutes from './furnitureRoutes.js';

const router = express.Router();

// Mount all route modules
router.use('/users', userRoutes);
router.use('/addresses', addressRoutes);
router.use('/products', productRoutes);
router.use('/search', searchRoutes);
router.use('/furniture', furnitureRoutes);
router.use('/cart', cartRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/orders', orderTrackingRoutes);
router.use('/my-orders', ordersRoutes);
router.use('/sellers', sellerRoutes);
router.use('/sellers', sellerProductRoutes);
router.use('/sellers', sellerOrderRoutes);
router.use('/sellers', promotionRoutes);
router.use('/profile', profileRoutes);
router.use('/community', communityRoutes);
router.use('/notifications', notificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/payment-methods', paymentMethodRoutes);
router.use('/returns', returnsRoutes);
router.use('/reviews', reviewRoutes);
router.use('/vouchers', voucherRoutes);
router.use('/help', helpRoutes);
router.use('/hyperlocal', hyperlocalRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/legal', legalRoutes);

export default router;
