import { ProductService } from '../services/ProductService.js';

// Sample products data
const productsData = [
  // Groceries
  {
    name: 'Fresh Milk 2L',
    description: 'Fresh full cream milk from local dairy. Perfect for your morning coffee or cereal. Sourced from trusted local farms.',
    price: 35.99,
    originalPrice: 42.99,
    discount: 7,
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop',
    ],
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 45,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.5,
    reviewCount: 23,
    socialProof: 'Bought 12 times today',
    isNew: true,
    isTrending: true,
    variants: [
      { name: 'Size', value: '2L', stock: 'in' },
      { name: 'Size', value: '1L', stock: 'in' },
    ],
  },
  {
    name: 'Free Range Eggs - 12 Pack',
    description: 'Farm fresh free range eggs',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 30,
    badges: [],
    rating: 4.7,
    reviewCount: 18,
    isTrending: true,
  },
  {
    name: 'Whole Wheat Bread',
    description: 'Freshly baked whole wheat bread',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 2,
    storeName: 'Melville Bakery',
    storeLocation: { lat: -26.1800, lng: 28.0100, suburb: 'Melville', city: 'Johannesburg' },
    distance: 2.3,
    stock: 'in',
    stockQuantity: 20,
    badges: [],
    rating: 4.3,
    reviewCount: 15,
  },
  
  // Braai Essentials
  {
    name: 'Premium Braai Pack',
    description: 'Beef, boerewors, and lamb chops',
    price: 299.99,
    originalPrice: 349.99,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 3,
    storeName: 'Sandton Butchery',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.2,
    stock: 'in',
    stockQuantity: 8,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.8,
    reviewCount: 42,
    socialProof: 'Bought 27 times today',
    isFlashDeal: true,
    isTrending: true,
    flashDealEndsAt: new Date(Date.now() + 4 * 60 * 60 * 1000), // 4 hours from now
  },
  {
    name: 'Boerewors 1kg',
    description: 'Traditional South African sausage',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 3,
    storeName: 'Sandton Butchery',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.2,
    stock: 'low',
    stockQuantity: 5,
    badges: [],
    rating: 4.9,
    reviewCount: 67,
    socialProof: 'Bought 35 times today',
    isTrending: true,
  },
  {
    name: 'Charcoal 5kg',
    description: 'Premium braai charcoal',
    price: 65.99,
    image: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 4,
    storeName: 'Rosebank Hardware',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.1,
    stock: 'in',
    stockQuantity: 15,
    badges: [],
    rating: 4.4,
    reviewCount: 28,
  },
  
  // Electronics
  {
    name: 'Wireless Earbuds',
    description: 'Premium sound quality wireless earbuds',
    price: 899.99,
    originalPrice: 1299.99,
    discount: 400,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 12,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.6,
    reviewCount: 89,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 6 * 60 * 60 * 1000),
  },
  {
    name: 'Smartphone Case',
    description: 'Protective case for latest smartphones',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 25,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.2,
    reviewCount: 34,
    isNew: true,
  },
  
  // Home & Kitchen
  {
    name: 'Non-Stick Frying Pan',
    description: 'Premium quality non-stick pan',
    price: 249.99,
    originalPrice: 299.99,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 10,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.7,
    reviewCount: 56,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 3 * 60 * 60 * 1000),
  },
  {
    name: 'Coffee Maker',
    description: 'Automatic drip coffee maker',
    price: 599.99,
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 7,
    badges: [],
    rating: 4.5,
    reviewCount: 41,
  },
  
  // Fashion
  {
    name: 'Cotton T-Shirt',
    description: 'Comfortable cotton t-shirt. Perfect for everyday wear. Available in multiple sizes and colors.',
    price: 199.99,
    originalPrice: 249.99,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
      'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&h=400&fit=crop',
    ],
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 18,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.3,
    reviewCount: 29,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 5 * 60 * 60 * 1000),
    variants: [
      { name: 'Size', value: 'Small', stock: 'in' },
      { name: 'Size', value: 'Medium', stock: 'in' },
      { name: 'Size', value: 'Large', stock: 'low' },
      { name: 'Size', value: 'XL', stock: 'out' },
      { name: 'Color', value: 'Black', stock: 'in' },
      { name: 'Color', value: 'White', stock: 'in' },
      { name: 'Color', value: 'Blue', stock: 'in' },
    ],
  },
  {
    name: 'Denim Jeans',
    description: 'Classic fit denim jeans',
    price: 449.99,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 12,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.6,
    reviewCount: 38,
    isNew: true,
  },
  
  // Baby & Kids
  {
    name: 'Baby Formula 900g',
    description: 'Premium baby formula',
    price: 189.99,
    image: 'https://images.unsplash.com/photo-1584837144859-1c61ad7b2f0a?w=400&h=400&fit=crop',
    category: 'Baby & Kids',
    storeId: 8,
    storeName: 'Kids Corner Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.8,
    stock: 'in',
    stockQuantity: 22,
    badges: [],
    rating: 4.8,
    reviewCount: 52,
    isTrending: true,
  },
  {
    name: 'Toy Building Blocks',
    description: 'Educational building blocks set',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    category: 'Baby & Kids',
    storeId: 8,
    storeName: 'Kids Corner Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.8,
    stock: 'in',
    stockQuantity: 15,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.7,
    reviewCount: 31,
    isNew: true,
  },
  
  // Health
  {
    name: 'Vitamin C Supplements',
    description: 'High strength vitamin C tablets',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 30,
    badges: [],
    rating: 4.4,
    reviewCount: 47,
  },
  {
    name: 'Protein Powder 1kg',
    description: 'Whey protein isolate',
    price: 349.99,
    originalPrice: 399.99,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 14,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.6,
    reviewCount: 63,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 2 * 60 * 60 * 1000),
  },
  
  // More products for variety
  {
    name: 'Fresh Vegetables Bundle',
    description: 'Mixed seasonal vegetables',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 20,
    badges: [],
    rating: 4.5,
    reviewCount: 19,
    isTrending: true,
  },
  {
    name: 'Chicken Breast 1kg',
    description: 'Fresh free range chicken breast',
    price: 79.99,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 16,
    badges: [],
    rating: 4.6,
    reviewCount: 27,
  },
  {
    name: 'Laptop Stand',
    description: 'Adjustable aluminum laptop stand',
    price: 399.99,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 9,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.5,
    reviewCount: 22,
    isNew: true,
  },
  {
    name: 'Yoga Mat',
    description: 'Premium non-slip yoga mat',
    price: 249.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 11,
    badges: [],
    rating: 4.7,
    reviewCount: 35,
  },
  {
    name: 'Running Shoes',
    description: 'Comfortable running shoes',
    price: 899.99,
    originalPrice: 1199.99,
    discount: 300,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 8,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.8,
    reviewCount: 71,
    isFlashDeal: true,
    isTrending: true,
    flashDealEndsAt: new Date(Date.now() + 7 * 60 * 60 * 1000),
  },
  
  // Additional Groceries
  {
    name: 'Tomatoes 1kg',
    description: 'Fresh red tomatoes',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1546097483-1c5c5c3b8c8b?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 35,
    badges: [],
    rating: 4.4,
    reviewCount: 16,
  },
  {
    name: 'Onions 1kg',
    description: 'Fresh yellow onions',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 40,
    badges: [],
    rating: 4.3,
    reviewCount: 12,
  },
  {
    name: 'Potatoes 2kg',
    description: 'Fresh potatoes',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1518977822534-7049a61ee0c2?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 28,
    badges: [],
    rating: 4.5,
    reviewCount: 21,
  },
  {
    name: 'Carrots 500g',
    description: 'Fresh orange carrots',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 32,
    badges: [],
    rating: 4.6,
    reviewCount: 18,
  },
  {
    name: 'Bananas 1kg',
    description: 'Fresh yellow bananas',
    price: 22.99,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 25,
    badges: [],
    rating: 4.7,
    reviewCount: 24,
    isTrending: true,
  },
  {
    name: 'Apples 1kg',
    description: 'Fresh red apples',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b27c92?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 30,
    badges: [],
    rating: 4.6,
    reviewCount: 19,
  },
  {
    name: 'Orange Juice 1L',
    description: 'Fresh squeezed orange juice',
    price: 28.99,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 20,
    badges: [],
    rating: 4.5,
    reviewCount: 15,
  },
  {
    name: 'Butter 500g',
    description: 'Premium butter',
    price: 42.99,
    image: 'https://images.unsplash.com/photo-1588165276332-0c1d0e3a0c8b?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 18,
    badges: [],
    rating: 4.4,
    reviewCount: 13,
  },
  {
    name: 'Cheese 250g',
    description: 'Cheddar cheese block',
    price: 38.99,
    image: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 22,
    badges: [],
    rating: 4.6,
    reviewCount: 17,
  },
  {
    name: 'Yogurt 1kg',
    description: 'Greek yogurt',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop',
    category: 'Groceries',
    storeId: 1,
    storeName: 'Sandton Supermarket',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.8,
    stock: 'in',
    stockQuantity: 24,
    badges: [],
    rating: 4.5,
    reviewCount: 20,
  },
  
  // More Braai items
  {
    name: 'Lamb Chops 1kg',
    description: 'Fresh lamb chops',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 3,
    storeName: 'Sandton Butchery',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.2,
    stock: 'in',
    stockQuantity: 10,
    badges: [],
    rating: 4.7,
    reviewCount: 33,
    isTrending: true,
  },
  {
    name: 'Ribs 1kg',
    description: 'BBQ pork ribs',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 3,
    storeName: 'Sandton Butchery',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.2,
    stock: 'in',
    stockQuantity: 8,
    badges: [],
    rating: 4.8,
    reviewCount: 45,
  },
  {
    name: 'Braai Sauce 500ml',
    description: 'Traditional braai sauce',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&h=400&fit=crop',
    category: 'Braai',
    storeId: 4,
    storeName: 'Rosebank Hardware',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.1,
    stock: 'in',
    stockQuantity: 15,
    badges: [],
    rating: 4.5,
    reviewCount: 28,
  },
  
  // More Electronics
  {
    name: 'USB-C Cable',
    description: 'Fast charging USB-C cable',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 30,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.3,
    reviewCount: 26,
    isNew: true,
  },
  {
    name: 'Phone Charger',
    description: 'Fast wireless charger',
    price: 199.99,
    originalPrice: 249.99,
    discount: 50,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 18,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.4,
    reviewCount: 31,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 3 * 60 * 60 * 1000),
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker',
    price: 449.99,
    originalPrice: 599.99,
    discount: 150,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 12,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.6,
    reviewCount: 58,
    isFlashDeal: true,
    isTrending: true,
    flashDealEndsAt: new Date(Date.now() + 5 * 60 * 60 * 1000),
  },
  {
    name: 'Tablet Stand',
    description: 'Adjustable tablet stand',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 14,
    badges: [],
    rating: 4.4,
    reviewCount: 22,
  },
  {
    name: 'HDMI Cable',
    description: 'High speed HDMI cable',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=400&h=400&fit=crop',
    category: 'Electronics',
    storeId: 5,
    storeName: 'Tech Hub Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.5,
    stock: 'in',
    stockQuantity: 20,
    badges: [],
    rating: 4.2,
    reviewCount: 19,
  },
  
  // More Home & Kitchen
  {
    name: 'Kitchen Knife Set',
    description: 'Professional knife set',
    price: 399.99,
    originalPrice: 499.99,
    discount: 100,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 6,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.7,
    reviewCount: 42,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 4 * 60 * 60 * 1000),
  },
  {
    name: 'Cutting Board',
    description: 'Bamboo cutting board',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 16,
    badges: [],
    rating: 4.5,
    reviewCount: 28,
  },
  {
    name: 'Dish Soap',
    description: 'Antibacterial dish soap',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 40,
    badges: [],
    rating: 4.3,
    reviewCount: 15,
  },
  {
    name: 'Kitchen Towels',
    description: 'Absorbent kitchen towels',
    price: 49.99,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=400&fit=crop',
    category: 'Home & Kitchen',
    storeId: 6,
    storeName: 'Home Essentials Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.5,
    stock: 'in',
    stockQuantity: 25,
    badges: [],
    rating: 4.4,
    reviewCount: 21,
  },
  
  // More Fashion
  {
    name: 'Hoodie',
    description: 'Comfortable cotton hoodie',
    price: 349.99,
    originalPrice: 449.99,
    discount: 100,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=400&fit=crop',
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 15,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.5,
    reviewCount: 36,
    isFlashDeal: true,
    flashDealEndsAt: new Date(Date.now() + 6 * 60 * 60 * 1000),
  },
  {
    name: 'Sneakers',
    description: 'Comfortable everyday sneakers',
    price: 599.99,
    originalPrice: 799.99,
    discount: 200,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 10,
    badges: [{ type: 'deal', text: 'FLASH' }],
    rating: 4.7,
    reviewCount: 52,
    isFlashDeal: true,
    isTrending: true,
    flashDealEndsAt: new Date(Date.now() + 8 * 60 * 60 * 1000),
  },
  {
    name: 'Backpack',
    description: 'Stylish backpack',
    price: 299.99,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c96a7?w=400&h=400&fit=crop',
    category: 'Fashion',
    storeId: 7,
    storeName: 'Fashion Forward',
    storeLocation: { lat: -26.1467, lng: 28.0433, suburb: 'Rosebank', city: 'Johannesburg' },
    distance: 3.2,
    stock: 'in',
    stockQuantity: 12,
    badges: [{ type: 'new', text: 'NEW' }],
    rating: 4.6,
    reviewCount: 29,
    isNew: true,
  },
  
  // More Baby & Kids
  {
    name: 'Baby Diapers',
    description: 'Premium baby diapers',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1584837144859-1c61ad7b2f0a?w=400&h=400&fit=crop',
    category: 'Baby & Kids',
    storeId: 8,
    storeName: 'Kids Corner Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.8,
    stock: 'in',
    stockQuantity: 30,
    badges: [],
    rating: 4.8,
    reviewCount: 67,
    isTrending: true,
  },
  {
    name: 'Baby Wipes',
    description: 'Gentle baby wipes',
    price: 39.99,
    image: 'https://images.unsplash.com/photo-1584837144859-1c61ad7b2f0a?w=400&h=400&fit=crop',
    category: 'Baby & Kids',
    storeId: 8,
    storeName: 'Kids Corner Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.8,
    stock: 'in',
    stockQuantity: 35,
    badges: [],
    rating: 4.6,
    reviewCount: 41,
  },
  {
    name: 'Stuffed Animal',
    description: 'Soft teddy bear',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    category: 'Baby & Kids',
    storeId: 8,
    storeName: 'Kids Corner Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 1.8,
    stock: 'in',
    stockQuantity: 20,
    badges: [],
    rating: 4.7,
    reviewCount: 33,
  },
  
  // More Health
  {
    name: 'Multivitamin',
    description: 'Daily multivitamin tablets',
    price: 129.99,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 25,
    badges: [],
    rating: 4.5,
    reviewCount: 38,
  },
  {
    name: 'Fish Oil',
    description: 'Omega-3 fish oil capsules',
    price: 179.99,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 18,
    badges: [],
    rating: 4.6,
    reviewCount: 44,
  },
  {
    name: 'Resistance Bands',
    description: 'Set of resistance bands',
    price: 149.99,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop',
    category: 'Health',
    storeId: 9,
    storeName: 'Health Plus Sandton',
    storeLocation: { lat: -26.1076, lng: 28.0567, suburb: 'Sandton', city: 'Johannesburg' },
    distance: 0.9,
    stock: 'in',
    stockQuantity: 13,
    badges: [],
    rating: 4.5,
    reviewCount: 27,
  },
];

/**
 * Seed products into the database
 */
export const seedProducts = async () => {
  try {
    const count = await ProductService.seedProducts(productsData);
    console.log(`✅ Seeded ${count} products successfully`);
    return ProductService;
  } catch (error) {
    console.error('❌ Error seeding products:', error);
    throw error;
  }
};

// If running directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedProducts()
    .then(() => {
      console.log('Seeding complete');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seeding failed:', error);
      process.exit(1);
    });
}

